import pandas as pd

#Saving data in a variable

readThis = pd.read_csv('C:/Users/Damaris-PC/AnalyzeProperties/DataArch/aluguel.csv', sep=';')

def meu_switch():
    validacao = True

    while validacao:
        z = int(input("Menu : "
                      "\n 1 : Property Type"
                      "\n 2 : Selection only residential "
                      "\n 3 : Open file TXT"
                      "\n 4 : Open file generated by excel"
                      "\n 5 : Open html file"
                      "\n 6 : Open web table"
                      "\n 7 : Sair \n"))
        if z == 1:
            filter()
        elif z == 2:
            selection_residential()
        elif z == 7:
            print("Programa encerrado")
            break
        else:
            print("opcao inválida")

def filter():
    propertyType = readThis['Tipo']
    type(propertyType)
    #inplace - quando seu dafault esta marcado como true,
    # ele modifica a variável a partir da execução do método,
    # não precisamos criar uma variável e atribuir a execução à ela.
    propertyType.drop_duplicates(inplace = True)

    #Criando um indice para visualizacao id
    propertyType = pd.DataFrame(propertyType)
    propertyType.index = range(propertyType.shape[0]) # retornar o número de registros de um DataFrame
    # df.index = range(len(df)) retornar o número de registros de um DataFrame
    propertyType.columns.name = 'id'
    print(propertyType)
def selection_residential():
    residential = ['Quitinete',
                   'Casa',
                   'Apartamento',
                   'Casa de Condomínio',
                   'Casa de Vila']
    # Vamos usar o isin(gera True e False) para selecionar, usamos a lista como corte
    selection = readThis['Tipo'].isin(residential)

    #Usaremos um método de seleção no DataFrame, de maneira que só tenhamos os registros que possuem a marcação True
    data_residential = readThis[selection]
    list(data_residential['Tipo'].drop_duplicates())
    #reformular o index para o corte de informacao da lista, gera o index novamento com nova contagem
    data_residential.index = range(data_residential.shape[0])
    print(data_residential.head(10))

    numeros = [i for i in range(11)]
    letras = [chr(i + 65) for i in range(11)]
    nome_coluna = ['N']

    df = pd.DataFrame(data=numeros, index=letras, columns=nome_coluna)
    selecao = df['N'].isin([i for i in range(11) if i % 2 == 0])
    df = df[selecao]
    print(df)

if __name__ == "__main__":
    print(meu_switch())